### ISSUE TITLE
Type "Unbound" is not callablestarpls error

### ISSUE THREAD

**Issue by daivinhtran** [withered-magic/starpls#1]
This is one of a few bugs I've found when trying the LSP.

When a rule instance is declared in a BUILD file, this error always appears.

![Screenshot 2024-01-17 at 10 53 03 AM](https://github.com/withered-magic/starpls/assets/13268391/c0ae403b-6d8e-4de8-938c-b4af762bd0b8)

**Comment by withered-magic** [comment]
Thanks for reporting! I haven't really started work on resolution of `load` statements yet, but a quick solution might be assign all names that appear as the `Any` type. That way at least it doesn't get super busy with `Unbound` errors everywhere. Will make sure to get this in soon!

**Comment by withered-magic** [comment]
In general though, the LSP doesn't really  support Bazel files just yet because most of the builtin functions/modules will be considered `Unbound`. One thing I'm planning on landing in the near future is loading builtins from a proto file generated by the [ApiExporter](https://github.com/bazelbuild/bazel/blob/b3c193aa2848ab693bceab9db51991d9e881269c/src/main/java/com/google/devtools/build/docgen/ApiExporter.java), at which point native functions/types should get resolved.

**Comment by withered-magic** [comment]
The errors here should be gone now! Basically while resolving load statements is still WIP, any name in a `load` statement will be assigned the `Any` type.
