### ISSUE TITLE
Warning: Type "ToolchainContext" is not indexable

### ISSUE THREAD

**Issue by hauserx** [withered-magic/starpls#252]
For sample rule implementation:
```
def _impl(ctx):
    info = ctx.toolchains["//:my_toolchain_type"].my_info
```
Getting:
![image](https://github.com/withered-magic/starpls/assets/32371993/c451cb76-e711-4dc2-9015-12bf2416c3aa)

**Comment by withered-magic** [comment]
Put up a temporary fix here: https://github.com/withered-magic/starpls/issues/252

However, the result of the indexing operation will be `Unknown` instead of `ToolchainInfo`, the full fix is blocked by https://github.com/withered-magic/starpls/issues/253 so will leave this open until that gets fixed as well

**Comment by withered-magic** [comment]
This should be fixed on master now!
